
//this file handle the little animation of the text of the differents text below the 3d models, it also handle the curvature of the text
//the logic is by me however a lot of values are generated by AI, mine weren't good for an irregular movement and not enough random

"use client";
import { useEffect, useMemo, useRef } from "react";
import { Text } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";

const FONT = "/fonts/Bestime.ttf";

//the goal here is to have an animation that depends on the character used
//inclinaisons in radians, very weak in order to not have 2 adjacent letters touch each other
//the animation also depend of the size of the font in order to be proportionnal
const SHIFT = 0.045;  //position shift of each letter horizontaly & verticaly proportionnal to fontSize (wobble)
const WAVE = 0.035;   // slow ondulation for each words depending of fontSize
const TILT = 0.022;   // radians, on 3 axis, tilts the letter to have a irreguliar visual

// we want a irregular pattern, so we do the sum of 2 sinusoids (1 is to regular for our case)
// we need x and y to not have the same speed otherwise it would be also to regular
// the values here are generated by IA
const DRIFT = {
  x:    [0.47, 0.71, 1.2, 0.8],
  y:    [0.51, 0.83, 1.0, 1.3],
  rotX: [0.44, 0.77, 0.9, 1.5],
  rotY: [0.58, 0.92, 1.4, 0.6],
  rotZ: [0.37, 0.69, 1.1, 0.7],
} as const;

type Axis = (typeof DRIFT)[keyof typeof DRIFT];

const drift = (t: number, phase: number, [sa, sb, pa, pb]: Axis) =>
  Math.sin(t * sa + phase * pa) * 0.6 + Math.sin(t * sb + phase * pb) * 0.4; //sum of the 2 sinusoids

// size reference of the table CHAR_W below
const FONT_SIZE = 0.22;
export const DEFAULT_FONT_SIZE = 0.248;
const GAP = 0.008;
const ARC_ANGLE = 0.96;

// the text itself is white, with two outline, one purple big, and one very very small in white
// i did this because the background is purple and purple on purple isnt good at all lmao we cound barely saw them
// to do this the letters draw themselves twice, white first then those with purple outlines
const LAYERS = [{ outlineColor: "white", outlineWidth: "14%" },{ outlineColor: "#5136f0", outlineWidth: "10%" },];

//advance width for each char, drei only reports its layout after render so too late to place letters manually
//we pre measured for this font and store it here as a fraction of an em, scaled by font_size const
//no need to say i didn't do it manually and used ai for this lmao
const CHAR_W: Record<string, number> = {
  " ": 0.055,
  "'": 0.049,
  ":": 0.079,
  ",": 0.066,
  ".": 0.074,
  "-": 0.117,
  "(": 0.094,
  ")": 0.095,
  "!": 0.080,
  "?": 0.125,
  "a": 0.150,
  "b": 0.145,
  "c": 0.126,
  "d": 0.155,
  "e": 0.137,
  "f": 0.119,
  "g": 0.155,
  "h": 0.146,
  "i": 0.071,
  "j": 0.125,
  "k": 0.128,
  "l": 0.072,
  "m": 0.212,
  "n": 0.140,
  "o": 0.141,
  "p": 0.144,
  "q": 0.141,
  "r": 0.147,
  "s": 0.120,
  "t": 0.103,
  "u": 0.143,
  "v": 0.129,
  "w": 0.201,
  "x": 0.127,
  "y": 0.144,
  "z": 0.137,
  "0": 0.157,
  "1": 0.123,
  "2": 0.141,
  "3": 0.144,
  "4": 0.157,
  "5": 0.146,
  "6": 0.152,
  "7": 0.132,
  "8": 0.141,
  "9": 0.152,
};
const DEFAULT_W = 0.137; //fallback case

const advance = (char: string, scale: number) => (CHAR_W[char] ?? DEFAULT_W) * scale;

export function measureWobblyWidth(text: string, fontSize: number): number {
  const scale = fontSize / FONT_SIZE;
  const gap = GAP * scale;
  return text.split("").reduce((w, char) => w + advance(char, scale) + gap, -gap);
}
//calculate how much the text curves at the end is to prevent the letters from overlapping and to provide a margin
export function measureWobblyRise(text: string, fontSize: number, curvature: number): number {
  if (curvature === 0) return 0;
  const angle = (ARC_ANGLE * curvature) / 2;
  const radius = measureWobblyWidth(text, fontSize) / (ARC_ANGLE * curvature);
  return radius * (1 - Math.cos(angle));
}

interface PlacedLetter {char: string;x: number;y: number;rotZ: number;phase: number;wavePhase: number;}

function placeLetters(text: string, fontSize: number, curvature: number, tilt: number, phase: number): PlacedLetter[] {
  const scale = fontSize / FONT_SIZE;
  const gap = GAP * scale;
  const width = measureWobblyWidth(text, fontSize);
  const radius = width / (ARC_ANGLE * curvature);
  // we treat courbature = 0 aside because in that case the radius is equal infinity and infinity x 0 = Nan in js cause js handle it like a true number and not a lim
  const flat = !Number.isFinite(radius);
  const chars = text.split("");

  let cursor = 0;
  return chars.map((char, i) => {
    const s = cursor + advance(char, scale) / 2 - width / 2;
    cursor += advance(char, scale) + gap;
    return {
      char,
      x: s,
      y: flat ? 0 : radius * (1 - Math.cos(s / radius)),
      // angle of the tangent, so that the letters slope along with the curve
      rotZ: flat ? 0 : Math.atan(Math.sin(s / radius)) * tilt,
      phase: phase + i * 0.6,
      wavePhase: phase + (i / Math.max(chars.length - 1, 1)) * Math.PI * 1.5,
    };
  });
}

// we put the text in the first plan to not have our 3d models hide the text (with the idle movement or zoom of the models it can happen)
// i putted 10 but we couldve just use a value >=2 it also work well 
const ON_TOP_ORDER = 10;

function useLabelMaterial(onTop: boolean) {
  const material = useMemo(
    () =>
      new THREE.MeshBasicMaterial({
        color: 0xffffff,
        side: THREE.DoubleSide,
        transparent: true,
        //letters never overlap each other, drawing order is set by renderOrder below, writing depth would conflict with it when they move
        depthWrite: false,
        depthTest: !onTop,
      }),
    [onTop]
  );
  useEffect(() => () => material.dispose(), [material]);
  return material;
}

interface Props {
  text: string;
  position: [number, number, number];
  phase?: number;
  fontSize?: number;
  curvatureFactor?: number;
  tiltFactor?: number;
  onTop?: boolean;
}

export default function TextAnimation({ text, position, phase = 0, fontSize = DEFAULT_FONT_SIZE, curvatureFactor = 1, tiltFactor = 0.4, onTop = false }: Props) {
  const material = useLabelMaterial(onTop);
  const letters = useMemo(
    () => placeLetters(text, fontSize, curvatureFactor, tiltFactor, phase),
    [text, fontSize, curvatureFactor, tiltFactor, phase]
  );
  const groups = useRef<(THREE.Group | null)[]>([]);

  useFrame(({ clock }) => {
    const t = clock.elapsedTime;
    const shift = fontSize * SHIFT;
    letters.forEach((letter, i) => {
      const group = groups.current[i];
      if (!group) return;
      const wave = Math.sin(letter.wavePhase + t * 0.4) * fontSize * WAVE;
      group.position.x = letter.x + drift(t, letter.phase, DRIFT.x) * shift;
      group.position.y = letter.y + drift(t, letter.phase, DRIFT.y) * shift + wave;
      group.rotation.x = drift(t, letter.phase, DRIFT.rotX) * TILT;
      group.rotation.y = drift(t, letter.phase, DRIFT.rotY) * TILT;
      group.rotation.z = letter.rotZ + drift(t, letter.phase, DRIFT.rotZ) * TILT;
    });
  });

  return (
    <group position={position}>
      {letters.map((letter, i) =>
        letter.char === " " ? null : (
          <group
            key={i}
            ref={(group) => { groups.current[i] = group; }}
            position={[letter.x, letter.y, 0]}
            rotation={[0, 0, letter.rotZ]}
          >
            {/* renderOrder need unique drawing order for the text, all outlines first, then all contours, left to right
            if left to depth sorting the outline of a moving letter could overlap the letters neightbor (hello neighbour reference)*/}
            {LAYERS.map(({ outlineColor, outlineWidth }, layer) => (
              <Text
                key={layer}
                font={FONT}
                fontSize={fontSize}
                fontWeight={900}
                color="white"
                outlineColor={outlineColor}
                outlineWidth={outlineWidth}
                anchorX="center"
                anchorY="middle"
                renderOrder={(onTop ? ON_TOP_ORDER : 0) + layer + i / letters.length}
                material={material}
              >
                {letter.char}
              </Text>
            ))}
          </group>
        )
      )}
    </group>
  );
}